# $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
  nerdFontsVersion: "3"
  tabWidth: 2
  sidePanelWidth: 0.33
  expandFocusedSidePanel: true
  statusPanelView: allBranchesLog
  mouseEvents: false
  # showDivergenceFromBaseBranch: arrowAndNumber
  # portraitMode: always
os:
  editPreset: "nvim-remote"
git:
  pagers:
    - colorArg: always
      # pager: delta --paging=never
      # --display=side-by-side-show-both
      externalDiffCommand: difft --color=always --skip-unchanged --syntax-highlight=on --tab-width=2
  commitPrefix:
      - pattern: "(\\w+-\\w+).*"
        replace : '$1 '
      - pattern: ".*" # The final fallthrough regex that copies over the whole branch name
        replace : '$0'
customCommands:
  - key: t
    command: tig show {{.SelectedSubCommit.Sha}}
    context: subCommits
    description: tig commit (`t` again to browse files at revision)
  - key: t
    command: tig show {{.SelectedLocalBranch.Name}}
    context: localBranches
    description: tig branch (`t` again to browse files at revision)
  - key: t
    command: tig show {{.SelectedRemoteBranch.RemoteName}}/{{.SelectedRemoteBranch.Name}}
    context: remoteBranches
    description: tig branch (`t` again to browse files at revision)
