gui:
  expandFocusedSidePanel: true
  theme:
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
    showBottomLine: false
    nerdFontsVersion: "3"
git:
  paging:
    colorArg: always
    # pager: delta --light --paging=never
    # externalDiffCommand: difft --color=always --display=side-by-side-show-both
    externalDiffCommand: difft --color=always 
